<?php

namespace Database\Seeders;

use DB;
use App\Models\PaketPekerjaan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PaketPekerjaanTable extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '001',
            'kode_sirup' => 11,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "TENDER, JASA KONSULTASI PENGAWASAN",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Jasa Konsultansi Pengawasan",
            'jenis_pengadaan' => "Tender",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '002',
            'kode_sirup' => 12,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "TENDER, JASA KONSULTASI PERENCANAAN",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Jasa Konsultansi Perencanaan",
            'jenis_pengadaan' => "Tender",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '003',
            'kode_sirup' => 13,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "TENDER, PEKERJAAN KONSTRUKSI",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Pekerjaan Konstruksi",
            'jenis_pengadaan' => "Tender",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '004',
            'kode_sirup' => 14,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "TENDER, PENGADAAN BARANG",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Pengadaan Barang",
            'jenis_pengadaan' => "Tender",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '005',
            'kode_sirup' => 21,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "NON TENDER, JASA KONSULTASI PENGAWASAN",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Jasa Konsultansi Pengawasan",
            'jenis_pengadaan' => "Non Tender",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '006',
            'kode_sirup' => 22,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "NON TENDER, JASA KONSULTASI PERENCANAAN",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Jasa Konsultansi Perencanaan",
            'jenis_pengadaan' => "Non Tender",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '007',
            'kode_sirup' => 23,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "NON TENDER, PENKERJAAN KONSTRUKSI",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Pekerjaan Konstruksi",
            'jenis_pengadaan' => "Non Tender",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '008',
            'kode_sirup' => 24,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "NON TENDER, PENGADAAN BARANG",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Pengadaan Barang",
            'jenis_pengadaan' => "Non Tender",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '009',
            'kode_sirup' => 31,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "E-CATALOG, JASA KONSULTASI PENGAWASAN",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Jasa Konsultansi Pengawasan",
            'jenis_pengadaan' => "E-Katalog",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '010',
            'kode_sirup' => 32,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "E-CATALOG, JASA KONSULTASI PERENCANAAN",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Jasa Konsultansi Perencanaan",
            'jenis_pengadaan' => "E-Katalog",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '011',
            'kode_sirup' => 33,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "E-CATALOG, PEKERJAAN KONSTRUKSI",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Pekerjaan Konstruksi",
            'jenis_pengadaan' => "E-Katalog",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '012',
            'kode_sirup' => 34,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "E-CATALOG, PENGADAAN BARANG",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Pengadaan Barang",
            'jenis_pengadaan' => "E-Katalog",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '013',
            'kode_sirup' => 41,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "Swakelola, JASA KONSULTASI PENGAWASAN",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Jasa Konsultansi Pengawasan",
            'jenis_pengadaan' => "Swakelola",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '014',
            'kode_sirup' => 42,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "Swakelola, JASA KONSULTASI PERENCANAAN",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Jasa Konsultansi Perencanaan",
            'jenis_pengadaan' => "Swakelola",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '015',
            'kode_sirup' => 43,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "Swakelola, Pekerjaan Konstruksi",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Pekerjaan Konstruksi",
            'jenis_pengadaan' => "Swakelola",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);
        DB::table('paket_pekerjaan')->insert([
            'nomor_matrik' => '016',
            'kode_sirup' => 44,
            'sumber_dana' => 'APBD',
            'tahun_anggaran' => '2025',
            'satker_id' => 1,
            'nama_pekerjaan' => "Swakelola, PENGADAAN BARANG",
            'waktu_paket' => "2023-01-01",
            'metode_pemilihan' => "Pengadaan Barang",
            'jenis_pengadaan' => "Swakelola",
            'nilai_pagu_paket' => "1000000",
            'nilai_pagu_anggaran' => "1000000",
            'nilai_hps' => "1000000",
            'ppkom_id' => 1,
            'daskum_id' => 1,
            'sekolah_id' => 1,
        ]);

        PaketPekerjaan::factory()->count(10)->create();
    }
}
